app = "mariposa-api"
primary_region = "fra"

[env]
  PORT = "8080"
  REDIS_URL = "redis://localhost:6379/0"
  MONGODB_URI = "mongodb+srv://ivalbat1:Zec311YkEDll4ein@cluster0.nsvzvnh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

[[services]]
  processes = ["web"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[processes]
  web = "uvicorn src.main:app --host 0.0.0.0 --port 8080"
