app = "mariposa-api"
primary_region = "fra"

[env]
  PORT             = "8080"
  BROKER_URL       = "amqp://guest:guest@mariposa-rabbitmq-autumn-moon-6671.internal:5672//"

[[services]]
  processes    = ["web"]
  internal_port = 8080
  protocol     = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port     = 80

  [[services.ports]]
    handlers = ["tls","http"]
    port     = 443

[processes]
  web          = "uvicorn src.main:app --host 0.0.0.0 --port 8080"
  celery_worker = "celery -A src.celery worker --loglevel=info"
  celery_beat  = "celery -A src.celery beat --loglevel=info"
