app = "mariposa-api"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [services.checks]
    type = "http"
    path = "/healthz"
    interval = "5s"
    timeout = "2s"
    grace_period = "30s"

  # Optional: if you want HTTPS on the default domain
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
