app = "mariposa-rabbitmq-autumn-moon-6671"
primary_region = "cdg"

[build]
  image = "rabbitmq:3-management-alpine"

[env]
  # Set your desired default user/pass here or via `fly secrets set`
  RABBITMQ_DEFAULT_USER = "guest"
  RABBITMQ_DEFAULT_PASS = "guest"

[[services]]
  protocol    = "tcp"
  internal_port = 5672

  # Health-check the broker port
  [[services.tcp_checks]]
    interval     = "15s"
    timeout      = "1m0s"
    grace_period = "5s"

[[services]]
  protocol      = "tcp"
  internal_port = 15672

  # Expose management on HTTPS + HTTP
  [[services.ports]]
    port     = 15672
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval     = "15s"
    timeout      = "1m0s"
    grace_period = "5s"
